### ISSUE TITLE
Clarity on singing button

### ISSUE THREAD

**Issue by Pleiotrope** [nebogeo/cricket-tales#116]
In the tutorial it should be stated that you just click the sing button once if a male sings in the video. Otherwise people may click constantly while the cricket is singing.  We only need one click per video

**Comment by nebogeo** [comment]
I just tried adding something to this effect, but I think it just ends up being more confusing. To some extent this depends on how fine grained the data needs to be, to be useful - is it enough for example to pull out all the videos that contain 1 or more singing events, rather than caring about how many or where they are in the timeline over the minute?

I'd imagine we'd do a lot of filtering of the data in this way - rather than going through it row by row...

**Comment by Pleiotrope** [comment]
Yes fair point, let's leave it.  There may be a few people who waste a lot of time clicking repeatedly on singing crickets, but if this is happening we'll see it in the data and we can act, and if it's just a few, we'll solve it in the way you suggest.
